if first_logical_expression == True:
    # ... some block of code ...
elif second_logical_expression == True:
    # ... another block of code ...
elif third_logical_expression == True:
    # ... yet another block of code
else:
    # ... the final block of code ...