CREATE VIEW database_name.view_name AS -- database_name is the name of the database where the view is created
SELECT
    column1, 
    column2, 
    ...
FROM
    some_table(s)...
WHERE
    some_conditions...